image:
    - Visual Studio 2017

branches:
    except:
        - gh-pages

environment:
    QTDIR: C:\Qt\5.13.2\msvc2017_64

install:
    - set PATH=%QTDIR%\bin;%PATH%
    - git submodule update --init --recursive

before_build:
    - ls C:\Qt\Tools\QtInstallerFramework
    - mkdir build
    - cd build
    - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"'
    - qmake ..\CuteMarkEd.pro

build_script:
    - for /r C:\projects\cutemarked-ng\app\translations\ %%i in (*.ts) do lrelease %%i
    - nmake
    - C:\projects\cutemarked-ng\win32installer\makeinstaller.bat

artifacts:
    - path: win32installer\installer.exe
      name: CuteMarkEd-NG Installer
    
