image:
    - Visual Studio 2019

branches:
    except:
        - gh-pages

environment:
    QTDIR: C:\Qt\5.14.2\msvc2017_64

install:
    - set PATH=%QTDIR%\bin;%PATH%
    - git submodule update --init --recursive

before_build:
    - mkdir build
    - cd build
    - qmake ..\CuteMarkEd.pro

build_script:
    - nmake
