echo Copying...
copy C:\projects\cutemarked-ng\build\app\release\cutemarked.exe C:\projects\cutemarked-ng\win32installer\package\io.qt.cutemarked.ng\data\
echo Deploying release...
windeployqt --release C:\projects\cutemarked-ng\win32installer\package\io.qt.cutemarked.ng\data\cutemarked.exe
echo Creating binary...
C:\Qt\Tools\QtInstallerFramework\3.1\bin\binarycreator.exe --offline-only -t C:\Qt\Tools\QtInstallerFramework\3.1\bin\installerbase.exe -p C:\projects\cutemarked-ng\win32installer\package C:\projects\cutemarked-ng\win32installer\installer.exe -c C:\projects\cutemarked-ng\win32installer\config\config.xml